fixtures:
  repositories:
    stdlib: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    concat: 
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
      ref: "2.2.0"
    archive: "https://github.com/voxpupuli/puppet-archive.git"
    openssl: "https://github.com/camptocamp/puppet-openssl.git"
    profiled: "https://github.com/unibet/puppet-profiled.git"
    systemd: "https://github.com/camptocamp/puppet-systemd"
  symlinks:
    shibboleth_idp: "#{source_dir}"
