---
language: ruby
cache: bundler
bundler_args: --without system_tests development
script: bundle exec rake test SPEC_OPTS='--format documentation'
sudo: false
matrix:
  fast_finish: true
  include:
  - rvm: 2.1.9
    env: PUPPET_GEM_VERSION="~> 4.0" STRICT_VARIABLES="yes"
notifications:
  email: false
